runtime: nodejs
env: standard
instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 1
env_variables:
  GOOGLE_CLIENT_ID: 'your-client-id'
  GOOGLE_CLIENT_SECRET: 'your-client-secret'
  GOOGLE_REFRESH_TOKEN: 'your-refresh-token'
  # Add other environment variables as needed